name: build

on: [push
    , pull_request
    ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
                    
      - name: Echo file changes
        run: |
          echo Changed files: ${{ steps.get_file_changes.outputs.files }}      
                        
      - name: Install Babashka
        run: |
          script/install_babashka
          
      - name: Test builds
        run: |
          script/test ${{ steps.get_file_changes.outputs.files }}  
